### ISSUE TITLE
Feature: Add AJAX to allow UI updates without refreshing the page

### ISSUE THREAD

**Issue by TomHooperr** [NickoOwen/bananabot#12]

**Comment by NickoOwen** [comment]
Thanks to @TomHooperr for all your work on this issue. As you said in our discussions, the way data was transferred between the client and server, not using dedicated endpoints to `POST` and `GET` data made AJAX basically impossible.
This has now been changed [in this Pull Request](https://github.com/NickoOwen/bananabot/pull/22) along with implementing the AJAX requests for the admin page.

Therefore I am closing this issue as it has been completed as part of https://github.com/NickoOwen/bananabot/pull/22

I will delete the branch after a bit of time has passed just in case it contains anything that might help solve future issues
