### ISSUE TITLE
Update the home and about webpages to a better format and replace the filler content with actual content

### ISSUE THREAD

**Issue by NickoOwen** [NickoOwen/bananabot#13]
The home and about webpages are currently very plain and simple and still contain majority Lorem Ipsum text as their content. This task is to rewrite the `index.html` and `about.html` pages to a new and more modern format, while also removing the filler content. The design is mostly up to the assignee, however the home page should state very obviously what time banana time is, and list the announcements somewhere on the page. The about page was created to contain information about the origin of banana time and anything else that might be interesting. It also helps to fill out the navigation bar.

Some good examples using Bootstrap can be found here: https://getbootstrap.com/docs/5.0/examples/

**Done:**
* The home page (`index.html`) has been rewritten to a more modern format and all filler content has been removed or replaced by actual content
* The about page (`about.html`) has been rewritten to a more modern format and all filler content had been removed or replaced by actual content

**Comment by BasilDimopoulos** [comment]
May I work on this? :D

**Comment by BasilDimopoulos** [comment]
Might start posing design updates here, wondering if @NickoOwen @peteryip like the direction of the new design or prefer the old one. I have added a potential logo for us as well, curious for all your thoughts!
![bananabot-new-landing](https://user-images.githubusercontent.com/62039344/211264034-603d41db-16cc-4ad3-94c6-1f8bb4f16c93.png)

**Comment by NickoOwen** [comment]
The great work @BasilDimopoulos did on this issue has now been implemented as part of https://github.com/NickoOwen/bananabot/pull/22
I am therefore marking this issue as closed. I will leave the branch there for a little while in case it comes in handy. I will delete it after some currently unknown period of time
