### ISSUE TITLE
Feature: Add an instant message option to the admin page

### ISSUE THREAD

**Issue by NickoOwen** [NickoOwen/bananabot#7]
Sometimes BB needs to send everyone a message. For example if banana time has changed because people are stuck in a meeting. The only way to do this through the UI currently is to schedule a message for the following minute, which is not very convenient.

This task is to add a new form to the admin page that allows an administrator to type a message and then click a send button, which then immediately sends a message. This may require a small rework of the `Announcement` classes to make `url` accessible as a class variable, however the implementation is up to the assignee.

**Done:**
* A form is now present on the admin page that can be used to immediately send a message as banana bot

**Comment by Zodius05** [comment]
Can I please be added as Assignee to this issue?

**Comment by NickoOwen** [comment]
Closing this issue as it has been completed. Good work @Zodius05 <3
